<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Progress_DomainLayer\Progress_DomainLayer.csproj" />
    <ProjectReference Include="..\Progress_RepositoryLayer\Progress_RepositoryLayer.csproj" />
  </ItemGroup>

</Project>
