// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Progress_DomainLayer.Data;

#nullable disable

namespace Progress_DomainLayer.Migrations
{
    [DbContext(typeof(SQLiteDBContext))]
    partial class SQLiteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Progress_DomainLayer.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Average")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Checked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test6")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test7")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test8")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Marks");
                });
#pragma warning restore 612, 618
        }
    }
}
