<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Database\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Progress_DomainLayer\Progress_DomainLayer.csproj" />
    <ProjectReference Include="..\Progress_RepositoryLayer\Progress_RepositoryLayer.csproj" />
    <ProjectReference Include="..\Progress_ServiceLayer\Progress_ServiceLayer.csproj" />
  </ItemGroup>

</Project>
